import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const json = x => JSON.stringify(x, null, 2) + '\n';
const roles = JSON.parse(read('core/agents.json'));
const version = JSON.parse(read('package.json')).version;
const expected = new Map();
function add(p, s) { expected.set(p, Buffer.isBuffer(s) ? s : Buffer.from(s)); }
function files(dir) {
  return fs.readdirSync(path.join(root, dir), { withFileTypes: true }).sort((a,b) => a.name.localeCompare(b.name))
    .flatMap(e => e.isDirectory() ? files(`${dir}/${e.name}`) : [`${dir}/${e.name}`]);
}
const preamble = `## Execution contract\n\nRead the DELFOS workflow skill before changes. Use official semantic-model-authoring for models/DAX and powerbi-report-cli for reports. Discover actual tools and verify the target in your own connection. Return concrete artifacts and evidence; mark unavailable checks NOT RUN. Only mutate within the authorized scope. For current documentation use Microsoft Learn through an available documentation MCP or web access.\n\n`;
for (const role of roles) {
  const body = read(`core/agents/${role.id}.md`);
  const lead = role.id === 'delfos-lead-squad';
  const copilotMeta = [`name: ${JSON.stringify(role.name)}`, `description: ${JSON.stringify(role.description)}`];
  if (role.id === 'delfos-architect') copilotMeta.push('handoffs: ' + JSON.stringify([{label:'Implement with Lead Squad',agent:'Delfos Lead Squad',prompt:'Implement the approved architecture through the DELFOS workflow.'}]));
  // Omit tools/model: inherit the user's host-enabled inventory and selected model;
  // plugin MCP names differ by host and registration. The user controls permissions.
  add(`.github/agents/${role.id}.agent.md`, `---\n${copilotMeta.join('\n')}\n---\n\n<!-- Generated by scripts/build.mjs from core/agents; do not edit. -->\n\n${preamble}Load .github/skills/delfos-workflow/SKILL.md. ${lead ? 'Use the native agent tool for specialist delegation when available; otherwise follow the sequential fallback.' : 'Complete the assigned domain task and return evidence to the caller.'}\n\n${body}`);
  const claudeMeta = [`name: ${role.id}`, `description: ${JSON.stringify(lead ? "Plan stages and review checkpoints for a multi-domain Power BI project; return specialist assignments to the main conversation, which owns delegation." : role.description)}`, 'model: inherit'];
  // Claude subagents cannot spawn other subagents. Main conversation runs orchestration.
  const adapter = lead
    ? 'You are a planning and checkpoint-review subagent. Return the stage plan and specialist assignments to the main conversation. Do not delegate or spawn subagents yourself. The main conversation owns execution through /delfos:delfos-workflow.'
    : 'You are a specialist subagent. Complete the assigned task and return to the main conversation; do not spawn subagents.';
  add(`plugins/delfos/agents/${role.id}.md`, `---\n${claudeMeta.join('\n')}\n---\n\n<!-- Generated by scripts/build.mjs. -->\n\n${preamble}Read \${CLAUDE_PLUGIN_ROOT}/skills/delfos-workflow/SKILL.md.\n\n${adapter}\n\n${body}`);
}
for (const p of files('core/skills')) {
  const relative = p.slice('core/skills/'.length);
  add(`.github/skills/${relative}`, fs.readFileSync(path.join(root,p)));
  add(`plugins/delfos/skills/${relative}`, fs.readFileSync(path.join(root,p)));
}
for (const p of files('.github/instructions')) {
  const text = read(p).replace(/^---\n[\s\S]*?\n---\n/, '');
  add(`plugins/delfos/skills/delfos-workflow/references/instructions/${path.basename(p)}`, text);
}
for (const p of ['preflight.mjs', 'validate-project.mjs']) {
  add(`plugins/delfos/scripts/${p}`, read(`scripts/${p}`));
}
add('.github/hooks/delfos-pbi-preflight-check.json', json({hooks:{PreToolUse:[{type:'command',command:'node .github/hooks/scripts/delfos-preflight.mjs',timeout:10}]}}));
add('.github/hooks/scripts/delfos-preflight.mjs', read('scripts/preflight.mjs'));
add('.github/hooks/scripts/delfos-validate-project.mjs', read('scripts/validate-project.mjs'));
add('plugins/delfos/hooks/hooks.json', json({hooks:{PreToolUse:[{matcher:'Write|Edit|MultiEdit|Bash|mcp__.*',hooks:[{type:'command',command:'node "${CLAUDE_PLUGIN_ROOT}/scripts/preflight.mjs"',timeout:10}]}]}}));
add('plugins/delfos/.claude-plugin/plugin.json', json({name:'delfos',version,description:'Power BI specialist agents and verified authoring workflows. Requires the Microsoft powerbi-authoring plugin for live tools.',author:{name:'Javier Armesto González'},license:'MIT',repository:'https://github.com/javiarmesto/DELFOS-An-Agent-Squad-PowerBI-GitHub-Copilot'}));
add('plugins/delfos/LICENSE', read('LICENSE'));
add('.claude-plugin/marketplace.json', json({name:'delfos-collection',owner:{name:'Javier Armesto González'},plugins:[{name:'delfos',source:'./plugins/delfos',version,description:'Power BI specialists for Claude Code; install powerbi-authoring separately.'}]}));
const check = process.argv.includes('--check');
let failed = false;
for (const [p, content] of expected) {
  const full = path.join(root,p);
  if (check) {
    if (!fs.existsSync(full) || !fs.readFileSync(full).equals(content)) {console.error(`Generated file out of date: ${p}`);failed=true;}
  } else {fs.mkdirSync(path.dirname(full),{recursive:true});fs.writeFileSync(full,content);}
}
// Detect stale generated files without deleting unrelated user content.
for (const dir of ['plugins/delfos/agents','plugins/delfos/skills','plugins/delfos/scripts', ...fs.readdirSync(path.join(root,'core/skills')).map(n=>`.github/skills/${n}`)]) {
  if (!fs.existsSync(path.join(root,dir))) continue;
  for (const p of files(dir)) if (!expected.has(p)) {console.error(`Unexpected generated file: ${p}; review and remove explicitly.`);failed=true;}
}
if (failed) process.exitCode=1;
else console.log(`${check?'Verified':'Generated'} ${expected.size} distribution files.`);
